package ru.bia.model;

import org.kie.api.definition.type.Label;

import java.util.Arrays;
import java.util.List;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Order implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@Label(value = "uuid")
	private String id;
	@Label(value = "Заказанные продукты")
	private List<ru.bia.model.Product> products;

	public Order() {
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public List<ru.bia.model.Product> getProducts() {
		return this.products;
	}

	public void setProducts(List<ru.bia.model.Product> products) {
		this.products = products;
	}

	public Order(String id,
                 List<ru.bia.model.Product> products) {
		this.id = id;
		this.products = products;
	}

    @Override
    public String toString() {
        return "Order{" +
                "id='" + id + '\'' +
                ", products=" + products != null ? Arrays.toString(products.toArray()) : "[]" +
                '}';
    }
}