package ru.bia.model;

import org.kie.api.definition.type.Label;

import java.util.Arrays;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Product implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@Label(value = "Id спецификации продукта")
	private String idSpec;
	@Label(value = "Характеристики (включая значения характеристик)")
	private java.util.List<ru.bia.model.Characteristic> caracteristics;

	public Product() {
	}

	public String getIdSpec() {
		return this.idSpec;
	}

	public void setIdSpec(String idSpec) {
		this.idSpec = idSpec;
	}

	public java.util.List<ru.bia.model.Characteristic> getCaracteristics() {
		return this.caracteristics;
	}

	public void setCaracteristics(
			java.util.List<ru.bia.model.Characteristic> caracteristics) {
		this.caracteristics = caracteristics;
	}

	public Product(String idSpec,
                   java.util.List<ru.bia.model.Characteristic> caracteristics) {
		this.idSpec = idSpec;
		this.caracteristics = caracteristics;
	}

    @Override
    public String toString() {
        return "Product{" +
                "idSpec='" + idSpec + '\'' +
                ", caracteristics=" + caracteristics != null ? Arrays.toString(caracteristics.toArray()) : "[]" +
                '}';
    }
}